Error propagation
golemfactory/golem-core-python pull request #134
Opened 2024-02-06 16:48 UTC by approxit

What I've done:
* Made that errors are now forwarded through the chain of managers to be raised in the activity creation step ultimately - a first explicit example is a failure in `get_allocation`.
* Made `.stop()` methods to be able to be called multiple times, as from now we have a case for stopping the manager when its background loop was already stopped due to a previously propagated error.
* Optimized time needed to raise a propagated error in the buffers, by making `Buffer.wait_for_any_items()` raise errors set by `set_exception`, so `get_requested()` will raise the given error instantly and will not wait to its debounce time.
* Made a few tweaks for RefreshingDemandManager loop.
* Updated the test cases

Notable remarks:
* To test `get_allocation` failures, just give `total_budget` in yaml a big number like 1000+

2024-02-07 07:02 UTC, shadeofblue requested changes

2024-02-07 07:02 UTC, shadeofblue commented on golem/utils/asyncio/buffer.py
> +                    logger.error(
same...

2024-02-08 08:16 UTC, lucekdudek commented on golem/utils/asyncio/buffer.py
> -
No `self._handle_error_if_empty()` here?

2024-02-08 08:18 UTC, lucekdudek approved these changes

2024-02-08 09:31 UTC, approxit commented on golem/utils/asyncio/buffer.py
> -
No, as `self.wait_for_any_items()` already contains `self._handle_error_if_empty()`.

2024-02-08 11:02 UTC, merged