Refactored modules structure
golemfactory/golem-core-python pull request #95
Opened 2023-04-18 17:42 UTC by approxit

Brace yourselves, massive change diff is coming!

What I've done:
- Moved code to structure that was mostly talked over with @lucekdudek
- Renamed `Model` into `DemandOfferBaseModel` as its more suited name than generic model

Imports are organized in following way:
- Each package have `__all__` in `__init__.py` that exports stuff that used outside
- In area of the same level in package, imports from `__init__.py` are not used, specific modules are chosen

That way, we can keep `__init__.py` clear enough to have stuff exposed for external use, when internal imports are not polluting everything.

For both scenarios I've chosen to use absolute imports, but maybe local imports for non-external stuff could be used too. We could also go with third path, where external imports are used from `__init__.py` but internal imports are imported separately from specific module.

Also, I'm not sure what suitable way could be done at the highest `core` level regarding imports. As modules are golem-api-based, it seems like its fair idea, but how about other modules like `golem_node`?

2023-04-19 06:38 UTC, lucekdudek requested changes

2023-04-19 06:38 UTC, lucekdudek commented on .github/actions/integration-tests-goth/action.yml
> +    - name: Stop goth network_api
Revert changes in this file

2023-04-19 06:38 UTC, lucekdudek commented on README.md
> +python3 -m golem_core allocation new 2 --driver erc20 --network_api rinkeby
Revert this change

2023-04-19 06:38 UTC, lucekdudek commented on examples/low_example.py
> +    """Use the direct interface of the activity_api"""
Change name of this file.
Revert Pydocs changes in this file.

2023-04-19 06:38 UTC, lucekdudek commented on examples/yacat.py
> +        #   This is a debit note for an unknown activity_api (e.g. from a previous run)
Revert

2023-04-19 06:38 UTC, lucekdudek commented on examples/yacat.py
> +        #   Destoyed activity_api from a previous run
Revert please

2023-04-19 06:38 UTC, lucekdudek commented on examples/yacat.py
> +        activity_data[activity]['status'] = 'old run activity_api'
Revert

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/cli/utils.py
> +    x.field_names = ["id", "address", "driver", "network_api", "total", "remaining", "timeout"]
`network`

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/activity_api/commands.py
> +        """TODO"""
TODO

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/activity_api/pipeline/__init__.py
> +)
Missing empty line at the end of the file?

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/activity_api/pipeline/activity_pool.py
>  class ActivityPool:
`activity` instead of `activity_api` in this class/file

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/activity_api/resources/pooling_batch.py
> +            #   This happens when activity_api is destroyed when we're waiting for batch results
`activity_api`

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/events/event_filters.py
> +        """TODO"""
todo

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/golem_node/golem_node.py
> +        """Shutdown. Stop collecting yagna events, close all core created with autoclose=True, close APIs etc."""
`core` ?

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/golem_node/golem_node.py
> +    #   Create new core
`core`?

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/golem_node/golem_node.py
> +        :param network: Payment network_api
`network`

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/golem_node/golem_node.py
>                               If `None`, next free ip will be assigned.
`network` in this pydoc

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/golem_node/golem_node.py
> +    #   Single-resource factories for already existing core
`core`?

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/golem_node/golem_node.py
>  class _RandomSessionId:
This file has some naming changes like _api or core, please revisit this file

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/network_api/resources/network.py
> +        #   activity_api can now be accessed from other nodes in the network_api
`_api`

2023-04-19 06:38 UTC, lucekdudek commented on golem_core/core/network_api/resources/network.py
> +            await activity_api.execute_commands(commands.Deploy(deploy_args))
`_api` in multiple pydcos in this file

2023-04-19 13:34 UTC, approxit commented
I haven't noticed that kind of mass-change fail. I've looked trough whole diff and found lots of other issues regarding this. It should be now fixed.

2023-04-25 08:04 UTC, lucekdudek approved these changes

2023-04-25 14:03 UTC, lucekdudek approved these changes

2023-04-25 16:10 UTC, merged